name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  ARTIFACTS_REPOSITORY: dswift-hat-stage-frontend-build-artifacts

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_HMI_LIBRARY }}

      - name: Setup NODEJS
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install --network-concurrency 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

      # TODO: ADD ENVIRONMENT UNIFICATION
      - name: Build deployment package
        run: PUBLIC_URL=/assets yarn build:staging:internal
        env:
          CI: true

      - name: Upload the build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_STAGING_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_STAGING_SECRET_ACCESS_KEY }}
        run: aws s3 sync build/ s3://$ARTIFACTS_REPOSITORY/latest/ --region eu-west-1
